name: Test Action
on:
  pull_request:

  workflow_run:
    inputs:
      environment:
        description: 'The environment to run the action in'
        required: true
        type: string
        options:
          - 'production'
          - 'staging'

permissions:
  contents: read
  pull-requests: write

jobs:
  ai-review:
    runs-on: ubuntu-latest
    name: AI-assisted Review
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run AI PR review
        id: ai-assisted-pr-review
        uses: ./
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
          PR_REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
